name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  to:
    description: 'chat id'
    required: true
  token:
    description: 'bot token'
    required: true
  status:
    description: 'status ["started", "failure", "success", "canceled"]'
    required: true
runs:
  using: 'node16'
  main: 'index.js'